FEATURE_MAPS:
      [
        [150, 150],
        [150, 150],
        [150, 150],
        [75, 75],
        [75, 75],
        [38, 38],
        [19, 19],
        [10, 10],
        [1, 1],
      ]
    STRIDES:
      [
        [8, 8],
        [16, 16],
        [32, 32],
        [64, 64],
        [100, 100],
        [300, 300],
        [300, 300],
        [300, 300],
        [300, 300],
        [300, 300],
      ]
    MIN_SIZES:
      [
        [30, 30],
        [60, 60],
        [111, 111],
        [162, 162],
        [213, 213],
        [264, 264],
        [264, 264],
        [264, 264],
        [264, 264],
        [264, 264],
      ]
    MAX_SIZES:
      [
        [60, 60],
        [111, 111],
        [162, 162],
        [213, 213],
        [264, 264],
        [315, 315],
        [315, 315],
        [315, 315],
        [315, 315],
        [315, 315],
      ]