MODEL:
  NUM_CLASSES: 5
  THRESHOLD: 0.3
  BACKBONE:
    NAME: "resNet50"
    PRETRAINED: True
    # ResNet101
    # OUT_CHANNELS: [512, 1024, 2048, 2048]
    #ResNet50:
    OUT_CHANNELS: [256, 512, 1024, 2048, 2048]
    # ResNet18:
    #OUT_CHANNELS: [128, 256, 512, 512]
    INPUT_CHANNELS: 3
  PRIORS:
    # ResNet101:
    #FEATURE_MAPS: [[60, 34], [30, 17], [15, 9], [1, 1]]
    # ResNet50:
    FEATURE_MAPS: [[60, 34], [30, 17], [15, 9], [1, 1]]
    # ResNet18:
    #FEATURE_MAPS: [[60, 34], [30, 17], [15, 9], [1, 1]]
    STRIDES: [[13, 7], [26, 14], [51, 29], [102, 58], [160, 90]]
    #STRIDES: [[13, 7], [26, 14], [51, 29], [102, 58], [160, 90], [320, 180]]
    MIN_SIZES: [[30, 30], [60, 60], [120, 120], [180, 180], [220, 220]]
    #MIN_SIZES:[[48, 30], [96, 54], [178, 100], [260, 146], [341, 192], [422, 238]]
    MAX_SIZES: [[90, 90], [130, 130], [180, 180], [220, 220], [270, 270]]
    #MAX_SIZES:[[96, 54], [178, 100], [260, 146], [341, 192], [422, 238], [480, 243]]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2]]
    BOXES_PER_LOCATION: [4, 6, 6, 6, 4]
INPUT:
  IMAGE_SIZE: [480, 270]
DATASETS:
  TRAIN: ("rdd2020_train",)
  TEST: ("rdd2020_val", )
SOLVER:
  MAX_ITER: 2000
  GAMMA: 0.1
  BATCH_SIZE: 16
  LR: 1e-3
EVAL_STEP: 2000
MODEL_SAVE_STEP: 2000
OUTPUT_DIR: "outputs/rdd2020_resnet50_plots"
DATASET_DIR: "/work/datasets"
