MODEL:
  NUM_CLASSES: 5
  THRESHOLD: 0.3
  BACKBONE:
    NAME: "resNet18"
    PRETRAINED: True
    #OUT_CHANNELS: [256, 512, 1024, 2048, 2048]
    OUT_CHANNELS: [64, 128, 256, 512, 512]
    # OUT_CHANNELS: [128, 256, 128, 128, 64, 64]
    INPUT_CHANNELS: 3
  PRIORS:
    FEATURE_MAPS: [[75, 75], [38, 38], [19, 19], [10, 10], [1, 1]]
    STRIDES: [[16, 16], [32, 32], [64, 64], [100, 100], [150, 150], [200, 200]]
    #MIN_SIZES: [[60, 60], [111, 111], [162, 162], [213, 213], [264, 264]]
    MIN_SIZES:
      [[30, 30], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264]]
    #MAX_SIZES: [[111, 111], [162, 162], [213, 213], [264, 264], [300, 300]]
    MAX_SIZES:
      [[60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [300, 300]]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
    BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]
INPUT:
  IMAGE_SIZE: [300, 300]
DATASETS:
  TRAIN: ("rdd2020_train",)
  TEST: ("rdd2020_val", )
SOLVER:
  MAX_ITER: 2000000
  GAMMA: 0.9
  BATCH_SIZE: 16
  LR: 3e-4
EVAL_STEP: -1
MODEL_SAVE_STEP: 5000
OUTPUT_DIR: "outputs/rdd2020_resnet18_final"
DATASET_DIR: "/work/datasets"
