MODEL:
  NUM_CLASSES: 5
  THRESHOLD: 0.3
  BACKBONE:
    NAME: "basic"
    PRETRAINED: False
    OUT_CHANNELS: [512, 1024, 512, 256, 256, 256]
    INPUT_CHANNELS: 3
  PRIORS:
    FEATURE_MAPS: [[38, 38], [19, 19], [10, 10], [5, 5], [3, 3], [1, 1]]
    STRIDES: [[8, 8], [16, 16], [32, 32], [64, 64], [100, 100], [300, 300]]
    MIN_SIZES:
      [[15, 15], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264]]
    MAX_SIZES:
      [[60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2]]
    BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]
INPUT:
  IMAGE_SIZE: [300, 300]
DATASETS:
  TRAIN: ("rdd2020_train",)
  TEST: ("rdd2020_val", )
SOLVER:
  MAX_ITER: 120000
  GAMMA: 0.9
  BATCH_SIZE: 16
  LR: 1e-3
EVAL_STEP: -1
MODEL_SAVE_STEP: 5000
OUTPUT_DIR: "outputs/rdd2020_resnet50_final_v0"
DATASET_DIR: "/work/datasets"
